FROM python:3.13.3

# Set working directory
WORKDIR /backend
COPY ./backend /backend
COPY ./frontend /frontend

RUN apt-get update && apt-get install -y default-mysql-client

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY shell/render_entrypoint.sh /render_entrypoint.sh
RUN chmod +x /render_entrypoint.sh
CMD ["/render_entrypoint.sh"]
