FROM python:3.13.3

# Set working directory
WORKDIR /backend
COPY ./backend /backend
COPY ./frontend/dist /frontend/dist

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY shell/docker_entrypoint.sh /docker_entrypoint.sh
RUN chmod +x /docker_entrypoint.sh
CMD ["/docker_entrypoint.sh"]
