"""add speakerId and constraint

Revision ID: 47b0293483d8
Revises: a4e4605f6ceb
Create Date: 2025-10-12 09:26:34.685735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "47b0293483d8"
down_revision: Union[str, Sequence[str], None] = "a4e4605f6ceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_audio",
        sa.Column("speakerId", mysql.TINYINT(unsigned=True), nullable=False),
    )
    op.add_column(
        "story_chunk_audio",
        sa.Column("speakerId", mysql.TINYINT(unsigned=True), nullable=False),
    )
    op.create_unique_constraint(
        "uq_story_audio_story_speed_speaker",
        "story_audio",
        ["storyId", "speedPercentage", "speakerId"],
    )
    op.create_unique_constraint(
        "uq_story_audio_chunk_story_chunk_speed_speaker",
        "story_chunk_audio",
        ["storyChunkId", "speedPercentage", "speakerId"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_story_audio_chunk_story_chunk_speed_speaker",
        "story_chunk_audio",
        type_="unique",
    )
    op.drop_constraint(
        "uq_story_audio_story_speed_speaker",
        "story_audio",
        type_="unique",
    )
    op.drop_column("story_chunk_audio", "speakerId")
    op.drop_column("story_audio", "speakerId")
    # ### end Alembic commands ###
