"""ini audio and config tables

Revision ID: 6a98e0fff3a4
Revises:
Create Date: 2025-09-23 18:39:46.677626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6a98e0fff3a4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio",
        sa.Column("url", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "format", sa.VARCHAR(length=255), server_default="WAV", nullable=False
        ),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audio_createdAt"), "audio", ["createdAt"], unique=False)
    op.create_index(op.f("ix_audio_updatedAt"), "audio", ["updatedAt"], unique=False)
    op.create_table(
        "config",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("sequence", sa.TEXT(), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_createdAt"), "config", ["createdAt"], unique=False)
    op.create_index(op.f("ix_config_updatedAt"), "config", ["updatedAt"], unique=False)
    op.create_table(
        "story",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_createdAt"), "story", ["createdAt"], unique=False)
    op.create_index(op.f("ix_story_updatedAt"), "story", ["updatedAt"], unique=False)
    op.create_table(
        "story_audio",
        sa.Column("storyId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("audioId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("speedPercentage", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audioId"], ["audio.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["storyId"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_audio_createdAt"), "story_audio", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_story_audio_storyId"), "story_audio", ["storyId"], unique=False
    )
    op.create_index(
        op.f("ix_story_audio_updatedAt"), "story_audio", ["updatedAt"], unique=False
    )
    op.create_table(
        "story_chunk",
        sa.Column("storyId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("position", mysql.TINYINT(), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["storyId"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_chunk_createdAt"), "story_chunk", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_story_chunk_storyId"), "story_chunk", ["storyId"], unique=False
    )
    op.create_index(
        op.f("ix_story_chunk_updatedAt"), "story_chunk", ["updatedAt"], unique=False
    )
    op.create_table(
        "wanikani_story",
        sa.Column("storyId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("level", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["storyId"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wanikani_story_createdAt"),
        "wanikani_story",
        ["createdAt"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wanikani_story_level"), "wanikani_story", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_wanikani_story_updatedAt"),
        "wanikani_story",
        ["updatedAt"],
        unique=False,
    )
    op.create_table(
        "story_chunk_audio",
        sa.Column("storyChunkId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("audioId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("speedPercentage", mysql.TINYINT(unsigned=True), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audioId"], ["audio.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["storyChunkId"], ["story_chunk.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_chunk_audio_createdAt"),
        "story_chunk_audio",
        ["createdAt"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_chunk_audio_storyChunkId"),
        "story_chunk_audio",
        ["storyChunkId"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_chunk_audio_updatedAt"),
        "story_chunk_audio",
        ["updatedAt"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_story_chunk_audio_updatedAt"), table_name="story_chunk_audio"
    )
    op.drop_index(
        op.f("ix_story_chunk_audio_storyChunkId"), table_name="story_chunk_audio"
    )
    op.drop_index(
        op.f("ix_story_chunk_audio_createdAt"), table_name="story_chunk_audio"
    )
    op.drop_table("story_chunk_audio")
    op.drop_index(op.f("ix_wanikani_story_updatedAt"), table_name="wanikani_story")
    op.drop_index(op.f("ix_wanikani_story_level"), table_name="wanikani_story")
    op.drop_index(op.f("ix_wanikani_story_createdAt"), table_name="wanikani_story")
    op.drop_table("wanikani_story")
    op.drop_index(op.f("ix_story_chunk_updatedAt"), table_name="story_chunk")
    op.drop_index(op.f("ix_story_chunk_storyId"), table_name="story_chunk")
    op.drop_index(op.f("ix_story_chunk_createdAt"), table_name="story_chunk")
    op.drop_table("story_chunk")
    op.drop_index(op.f("ix_story_audio_updatedAt"), table_name="story_audio")
    op.drop_index(op.f("ix_story_audio_storyId"), table_name="story_audio")
    op.drop_index(op.f("ix_story_audio_createdAt"), table_name="story_audio")
    op.drop_table("story_audio")
    op.drop_index(op.f("ix_story_updatedAt"), table_name="story")
    op.drop_index(op.f("ix_story_createdAt"), table_name="story")
    op.drop_table("story")
    op.drop_index(op.f("ix_config_updatedAt"), table_name="config")
    op.drop_index(op.f("ix_config_createdAt"), table_name="config")
    op.drop_table("config")
    op.drop_index(op.f("ix_audio_updatedAt"), table_name="audio")
    op.drop_index(op.f("ix_audio_createdAt"), table_name="audio")
    op.drop_table("audio")
    # ### end Alembic commands ###
