"""add source to story

Revision ID: a4e4605f6ceb
Revises: f1f8e215f1c4
Create Date: 2025-09-24 02:43:27.245553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e4605f6ceb'
down_revision: Union[str, Sequence[str], None] = 'f1f8e215f1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('source', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'source')
    # ### end Alembic commands ###
