"""rename story name to title

Revision ID: f1f8e215f1c4
Revises: 6a98e0fff3a4
Create Date: 2025-09-23 19:44:03.193310

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f1f8e215f1c4"
down_revision: Union[str, Sequence[str], None] = "6a98e0fff3a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story", sa.Column("title", sa.VARCHAR(length=255), nullable=False))
    op.drop_column("story", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story", sa.Column("name", mysql.VARCHAR(length=255), nullable=False))
    op.drop_column("story", "title")
    # ### end Alembic commands ###
